### ISSUE TITLE
How to Generate Litecoin Address from Ltub?

### ISSUE THREAD

**Issue by GoekhanDev** [karask/python-litecoin-utils#6]
Hello,

I'm working on a payment gateway, my ledger native segwit wallet provided me with a Ltub public key lookin like this:

>Ltub2Zn7k8vFeTjWP8aefAjLJfRRigihzTRjEFVuEBGpKiAVX15K2GVgr73cqLSYgGtKnHgnucwevUmUXZARKhwACGPCtmpcfS9ELhMyqNq2gwz

I want to create P2WPKH Receiving Addresses.

Thanks in Advance.

**Comment by karask** [comment]
Hi @GoekhanDev 

I am afraid I am not supporting this library. I might look at it if I have some time but it won't be anytime soon.

**Comment by GoekhanDev** [comment]
I solved with a different library, no need for it anymore. thanks.
