### ISSUE TITLE
OverflowError: int too big to convert

### ISSUE THREAD

**Issue by tomjeannesson** [karask/python-litecoin-utils#7]
Hello,

Is it possible to fix this for litecoin too? (cf [this issue](https://github.com/karask/python-bitcoin-utils/issues/36))
Otherwise is there a workaround I could implement?

Thank you for your time.

**Comment by karask** [comment]
Hi @tomjeannesson 

Just merged your PR.

**Comment by tomjeannesson** [comment]
Thanks!

**Comment by tomjeannesson** [comment]
@karask any idea when this will be part of the python module?

**Comment by karask** [comment]
Just updated to 0.5.5 in pypi.

**Comment by tomjeannesson** [comment]
> Just updated to 0.5.5 in pypi.

Thanks!
