### ISSUE TITLE
Request for Mnemonic Seed Phrase Feature

### ISSUE THREAD

**Issue by hakanoktay** [karask/python-litecoin-utils#9]
I am trying to generate a mnemonic seed phrase, but I couldn't find or use such a feature in the current module. Therefore, I believe it would be highly functional to add a feature like `private_key.to_mnemonic()`.

By adding a new function, for instance, the to_mnemonic function, users could be given the ability to generate a mnemonic seed phrase from a private key. The proposed feature could be used as follows:

```
...
private_key = PrivateKey()
seed_phrase = private_key.to_mnemonic(num_words=12)
print("Mnemonic Seed Phrase:", seed_phrase)
...
```

**Comment by karask** [comment]
Hi @hakanoktay, I don't support the litecoin library for some time now. If you want, feel free to create a PR and I can merge it.

**Comment by hakanoktay** [comment]
Hi @karask, thank you for your answer. Unfortunately I don't understand cryptography. I tried a bit yesterday but I think it's beyond my neurons and  finally gave up :)

But i use the module, it was very helpful for me. it saved me from a lot of confusion, from a lot of things I didn't know. 
thank you. (ツ)

**Comment by karask** [comment]
You are welcome @hakanoktay .  I still maintain the Bitcoin library, so feel free to check it out.
